version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - apt-get update
      - apt-get install -y unzip
      - curl -fsSL https://releases.hashicorp.com/terraform/$(curl -fsSL https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M .current_version)/terraform_$(curl -fsSL https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M .current_version)_linux_amd64.zip -o terraform.zip
      - unzip terraform.zip -d /usr/local/bin/

  pre_build:
    commands:
      - echo "Pre Build Completed"

      # Optionally, you can configure AWS CLI here if needed.

  build:
    commands:
      - echo "Infra Build"
      - ls
      - terraform init
      - terraform validate
      - terraform plan -out=tfplan
      - echo "Application Build"
      - terraform apply -auto-approve

  post_build:
    commands:
      - echo "Executing post-build commands"
      - zip -r main.zip main.py
      - aws s3 cp main.zip s3://awss3bucketuploadartifact/
      # You can add additional post-build steps or notifications here.
# artifacts:
#   files:
#     - path/to/your/terraform/code/tfplan
